var d=new Date();
//console.log(d.getUTCTime());
console.log(d.getUTCFullYear());
var month=["Jan","Feb","Mar","Apr","May","June","Jul","Aug","sep","Oct","Nov","Dec"];
console.log(month[d.getUTCMonth()]);
console.log(d.getUTCDate());
console.log(d.getUTCHours());
console.log(d.getUTCMinutes());
console.log(d.getUTCSeconds());
console.log(d.getUTCMilliseconds());
console.log(d.getUTCDay());