var width=10;
var length=20;
var heigth=40;
var breadth=30;
var area,perimeter;
area=width*length;
perimeter=2*(length+width);
areaoftriangle=(heigth*breadth)/2;
console.log("Area of rectangle "+ area);
console.log("Perimeter of the rectangle "+ perimeter);
console.log("Area of trinangle "+areaoftriangle);